# Certificate Let's Encrypt pour phpmyadmin.kubesecurebox.com
# ===========================================================
# DNS Challenge (ClusterIssuer Cloudflare) - fonctionne même si l'hôte n'est exposé que sur Tailscale
# sync-wave: -1 pour que le Certificate soit créé avant l'Ingress (cert-manager émet le secret en async)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: phpmyadmin-kubesecurebox-tls
  namespace: phpmyadmin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: phpmyadmin-kubesecurebox-tls
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - phpmyadmin.kubesecurebox.com
