apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: personal-rag
  labels:
    app: rag-api
spec:
  selector:
    app: rag-api
  ports:
    - port: 8000
      targetPort: 8000
      name: http
