---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-secrets
  namespace: personal-rag
spec:
  encryptedData:
    TELEGRAM_ALLOWED_USER_IDS: AgDC+aVRvtP+uHFx/5WIkuPLmX01bnxPZapdmZa8JvXhxTdF29vYZF2uf50Ttusf/lVBtz3dg4XYMdx7Y+lzEzuwZ3mQ+tRQHy3nSDHuf41GTwX7sSxGJjhPyS4IMGpl1KlJS7lGPMd7TfF0xf4MIMT83R9odl5/4U4RJlqOu3998/wVpEqjd1Ly3qg82eHDKv/3Tl/A2EA6I7t4fBAEYjxIEeB39QBp3GG3eaiVLPWs5V38JSDhVoCzOxghK2PuftDpf1Q3PvypskHi4hPepVvz1JPZKE1flbKo0q1T+7eVXYYkSCpdYS7eZA4jPXGQCSb4Sj18z9Z+NaaJjlizD8F1TMW7j0Op/wG0R9iRDyWeWIlH3xD1diMJkNAZvHWcteAIGPNjX1Ii3lLzHMJDKtnuNVVSR8dFXlTlKhzK1+9EGnkmbjZdPri3/gzRVRg3vKNVZizX2XAlrOj9xs5SW0dA7g/AmzZ9BDVn9udSxQBv3d3Oa3kMMLzUIxzZ4scUkyxFX0EIf0gXVS8CahyzQ2FXqbmH12bR0utHQrYtqIEm0TV1y48cpWqsnzKZoRTNo5rgiGMtPJ30v4hwG97rChsndXW3ZbL+pNma4iBAwlVB1lYyu85X81RUo5KH2IOcZ5SjgpeoX2Ro9As510p+LQCeDga/p7TnNVX8agcCB9M1WgO1v/CuHk/9yRdXZu+YebodhamZq/n3t2w8
    TELEGRAM_BOT_TOKEN: AgC1zVepNQyLPU3DTh837pqpbgPjlM6p1A89mmZ/puqhsmfAGYD2KRQWlHo4dZSas/R/zK1Ae4qmaDM/IhiMfM/jKegI997uVDAHjFJgOpUnKITAuprAs73PL0lBEfffzAyjNJPMfO5JYRUoqgiDp7LHKF2ylrjhz+1AVwjAgK5rLSb6WeUFEa8wZrNy/JXi9Pw/r8nnX0WQmfeF46lMjcRBKByQwcLWlRwjXFGlL0NMWjcpqq3+1HFXdHn6fnBmhJoYJUgkVqaYxn1Pg2WbQH3Buzi5rzntbowTniDju8+AcaFl/vQyF9fXIuYJj/3Viao9tlCLnBK65IiWe8b/oDFb2vdst8t5vDhA80d9Jv8qg36BD2izqQGBqvytVWZm3jUvAE74Cfr4RILbSvES6AcLRd2C/15FLGftfEWaoxhZFszT13dVj1CR1lu/Q5Bq7+WEhyV2ggy8Ya1bbARQjYc+0xD9AXWZDLhlQmN0nvIiJqsqRJS8Qa7htjawNVtpC/AkPEQ7HfmvdUFd3EBG6L777Rf7DTuAeeq3YTYLAyELEP435gVlK6++qA/d4z6f9snhw3S9dNfIo5YKzMr5FpPatq3Oc7z2W+YyvsCPQsg2E950u5OKqsYXBADX4YSjagBtbv8jGBkGrVqPBUfSxd1jl24iD/GWQLPItxCwiBMkafF6Jb3+B9pcRv0XJsEytkzHi8YWsVZUKE+pEJ9d2zHcZuNGXUxY/yZ3yEMMQ694JN/tzt8jCFtFdSWU3Ftj
  template:
    metadata:
      creationTimestamp: null
      name: telegram-secrets
      namespace: personal-rag
