# Certificate Let's Encrypt pour sheets.kubesecurebox.com
# ========================================================
# sync-wave: -1 pour que le Certificate soit créé avant l'Ingress (cert-manager émet le secret en async)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nocodb-kubesecurebox-tls
  namespace: nocodb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: nocodb-kubesecurebox-tls
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - sheets.kubesecurebox.com
