# Namespace nocodb (app métier)
# ==============================
# sync-wave: 0 pour que le namespace soit créé avant les autres ressources du dossier.
apiVersion: v1
kind: Namespace
metadata:
  name: nocodb
  labels:
    app.kubernetes.io/name: nocodb
    app.kubernetes.io/part-of: kubesecurebox
  annotations:
    argocd.argoproj.io/sync-wave: "0"
