---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nocodb-auth-secrets
  namespace: nocodb
spec:
  encryptedData:
    jwt-secret: AgCigWzjgI9iGnAF5YnU5AxRd4PdnBTMB7vpBlN2k6VAs75P3eursJy5EXeaWVcY7TnoqkyuSq1tsMDzu+ST1qP3q8CMJ01lyExPEiPe+VvEJxvb10/9rPf10GzJD2ZOOrQzCLgEsv4JKdYuAtVULMEGQu344V6vu/8Ypqm24zdDQdkJlCpwNcsqdoIgC8++qQENcI9RGN38BmvGIOa6TzThEQCifbOuDbqmUDPjIueRC2i6TnCTr3ADpi6efsg36Wluqvw3pD2K8iSBdzeM7w9n5peobLSMvKDMIuPnc6/MMc0fVMM1rSS2BCIK4TRqD+ZWY2AMDRnxi4r7/8sd+fiU4pvXI1kjmXCR4wzYbMtmhbyhkUk//88v73sraJw6ApQq36xoYFeeP54b6xoVNUsGde1CzdyClLIr4uUvXlpuVXzvJc9u3V+/eFhlSSXFuctkKfv3LFoY8HFshzql6GBsK7GYuxKRdYQaZlpdkww9fVqad8ka5Vv6MOTS3wCWlx3tOOaw4MqBjz5S/kgXovt/uHNB0lMZOCf0wGGIf8La+cDEl7RcoM5QjW+vqTlX8F1EFZalMaMSIe2SS5UQWL9Q9bWEPqc8Gwkjc62NH7gxadXbF/RzUmMH1KlZD6+4y++2b9UXjhCZ4udlwxl28eqPslCggKF+9Z3r9GCb7FighIYT0M8BuMyCNRKBqOptyOnqcxhXsoGVXTUpHgszHocxEY3lppfkRD7+LnE0CuWgTdSbMYHldtKyrSV6xelFI7njdhs8uPonZrrCGvs6hd/V
  template:
    metadata:
      creationTimestamp: null
      name: nocodb-auth-secrets
      namespace: nocodb
