apiVersion: v1
kind: Service
metadata:
  name: stock-analyzer-frontend
  namespace: stock-analyzer
  labels:
    app: stock-analyzer-frontend
spec:
  selector:
    app: stock-analyzer-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
