# ServiceAccount Portainer - utilisé par le Deployment (accès API Kubernetes)
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-sa-clusteradmin
  namespace: portainer
  labels:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/part-of: kubesecurebox
