# Certificate Let's Encrypt pour matomo.kubesecurebox.com
# =======================================================
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matomo-kubesecurebox-tls
  namespace: matomo
spec:
  secretName: matomo-kubesecurebox-tls
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - matomo.kubesecurebox.com
