# Sealed Secret : credentials MySQL pour Matomo
# =============================================
# À créer AVANT le premier déploiement. Remplace tout ce fichier par la sortie de la commande ci-dessous.
#
# 1. Contexte kubectl pointant vers ton cluster.
# 2. Générer un mot de passe MySQL et sceller le secret :
#
#    MYSQL_ROOT_PASSWORD=$(openssl rand -base64 32)
#    MYSQL_PASSWORD=$(openssl rand -base64 32)
#    MYSQL_DATABASE=matomo
#    MYSQL_USER=matomo
#
#    kubectl create secret generic mysql-credentials \
#      --from-literal=mysql-root-password="$MYSQL_ROOT_PASSWORD" \
#      --from-literal=mysql-password="$MYSQL_PASSWORD" \
#      --from-literal=mysql-database="$MYSQL_DATABASE" \
#      --from-literal=mysql-user="$MYSQL_USER" \
#      --namespace=matomo \
#      --dry-run=client -o yaml | kubeseal -o yaml
#
# 3. Copier la sortie complète ici (à la place du YAML ci-dessous), sauvegarder, puis push.
#
# Sans cette étape, le StatefulSet MySQL restera en CreateContainerConfigError (Secret manquant).
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-credentials
  namespace: matomo
spec:
  encryptedData:
    # TODO: Remplacer par la sortie de kubeseal
    mysql-root-password: AgAsV+YP06lGweUAxb+u/4MbYVMQqw6BC8HxMuTkRzvROM98nIWaaVQmmYppk33SfmDAE1mxGpkuiFnXT1rC+Ld4ElfuDuxYEsG6ZgBJERMegErN3LW/WJ8Uh9k4LU8wsGaIiK8IUa3g9iWAa876W5QexawWSWp5R2uvbQqsHgecebsQmIIrqAvq2z6Xm0/Pfb/Bx5rEF3W8kHul64KKHkRqR1r4DdxbQKWZRYBo1GVxYd2bdl5ulI5+dSLjs4WaeoPTTmpUOn6/ywTWSNTSzZQj2oY2B74WUXg6qQ3zS8YLVAp3k/vVau3rNxboc6r947RMouDGFPOyWGdfVBQwqozcjQ2EozM/ar0g5ugqHKbZ7hXoOTCiGygKjI7oMGHhrUtDhX/8MH2JNtTKUtmqBxAx34JVzRVK1l2x4+Wub8k0uHSg9TgAmpxS8rVd4DEuCIim52H5iqxxsxTrQotjGitgYd1BPq7IO2w2ldkFCYk7DimyrYCQgrtxsBXh4BVfg89CCxDZhIwJi9RwSzwRyNVf912x2+Ind1S5PXk2Lnh9+5QRYyyetsq1bU8H1ZbXvvxFHMKlR3RxUaJwBr79DCRWsLm+5VwKLDvuwcH4XUKGzTcXm/x0vi/5LhJeg55KYe20b1zMMKPpiQw04aVodlwrQkiRyrLnVUvQLPG+MeksA9/+h3B9PCBP31nGD/cQoDMydPE/XCfBTMwS3ktLF1POwNBoAmxAXvYZZjmz14JVcVk4JGN+6ZI5hiurRg==
    mysql-password: AgCpYuhR6PWU63NbKYYJSa38oWzEHNdkRQZBef4gVGBPoGrqMd1SjI4UiUro9CORA9xaC4aeVJXsE/MrN99fN3ihQ/U0baSQJIkCJQJ2zElb6n3646HINzpSGFgKEWKe0j7WJ3fut3RnDB/wC6OMizGEuhH6qn/fEO8sOxs4C5BPaYqc+WtPTlXLnx28Bbua9WDK8eJmqR0Z2bKhcmqCqycDx0GkzabtKkXrQG1BafZIneJWrSdBTf0iI+6nIZH2QsMrCiK0Q0jMxjuWmWZcZ1WqRQeTUj6BpEuEeWV67/twPXJFq+Gc9R1L4ip2EotKKroIK2GmA6XzuZDR+w3LDqotjdFnEk/M9ITMwA98i4vV6u/CB8ZPBI+UbH1ln4mDPIGa5Zq70ERiPBv5eF/pzyBxPPlsu4h7Z+U6nKVUZHMTJoygpVfJCcYfNsUMRU5fnbJd3GIWVmvMop+Q0y+8kASHqpphi+b9E+WL32SZ6nMrJN5VbkXA9QtStGwp4K3P/eM38cbXyA7N6WFw6PVmTq/i4Q+uafAjIunA2OwkJzb4xdnJSExQwjdNHDZt4Vh7hSj1hU497DoB/TJU08SA2XDtuuNaMa0KnQckbz0lfLKppB3zvFrQ++eu6ZN6khP8nZj7rfJWAdDHD6/s+0RKr3nGjHNzclV03xj/28zDAFNf4VUq1F/OGjmxsyzQVD2/UvznYR4l/RkCBwXV7bsOVMgrz07mUPEGKR/bY8lECJQB0hDti934V8MUHx/u7g==
    mysql-database: AgAeA24r/IY/us+RgdmwTk+K6O7lNQqTHX1led368bLxUTsimzkOCMRpN0mtVzfZan7RUYyViN63Cs53npCUFAzi+JptrLugVuonDVTsI0dOhs9cOiBVzZ3snzGn0if1uqZvs00qdkW0F+vXcVaj3lVTBLLwjVtupxhuaurlReysBfFHjpoTwSJ5wkuAZdY/ClHBRc9TwdxCWEH+pUacVrrHiHCpPK2CHdEgn6qToXG21iin+F7vyG7DQSgbMqt9rI/KyAPdrErBG/SzheN6WGrMKTzGhx/n4+1BTkfK7PwJQFkg9Py06zOaSHdq0Yxyq2QHpEK2py9U1dDe41v7gHuxMlTIkiXa0Vp0FPWoZDIi2IddW7kVG2OT51/TAelu6bJGf4tkRwYIp4rafOQ5Ev3G9XVZM6NKWEoXhyXKRN0lHxPn146hCAdYI7mVD+gBIkK4y4INs1U5dE/dRRgydkHaYc1Qyari+54lFnP6T2s6RGFWqmwZ6TPsM4xB5qrkGCokfDwWzDRzfrul8GoGYOmkGxFMl93mn97fsdSZJSgohpJgiuQBsO8xC7aCPoCZFTjQ04wxJS8ZSHlgLhk2M9NUY86HvExLQz2lejkUTqZx0Gg23OwPafscuYTHHKsy4MBYs0gGySJNqZyzMByPU6bqdellujzfcGPNdvK/hMTSivJ6aEruM+TTs5NR10dvs14CDTAWnrc=
    mysql-user: AgBa3wk7gphw6m3DKaA2fYSY76CssLZvwY+vvvmAln9WmUi7+lnhuzIgQe4rZWs+1FyHEoJk3FOuMyDxBUynfrclJhr0aSfLFR3JJt4CXl0UIyJKs5sCKZxY+eCv+7ouC2RLlj/DWR3zvVvgw4C6REOor3GqOJsvdlq3YjGMiEznmlVacckSpCQ/9gfE1rjMoJKnFQnOw9DIDDTkyyVc6nIQNr2w9BuAez41Aj9pgup0QmUmKAtUdyTbc3vuthfVPEWHT2rJOZfq8ckFs19d6rnXYbFI9909L/qpgj/Ap75PTH4uW1WJcjlFPc2ulnDKr5fQ8z9Skh56oBqfawuQcvSsNnePL1F33VRjKkfRLIo9ueVfqUGpuSSX2BU+jRksJNOUk7TM+/r58EBCmC7X2CFKDnwyjQOXgLPBMxyqlNBPB5/b4ZNdwBeuKSXAkcZO9CsjYEiivcprYxd39hfr/gdjQbyckQgT76UmX+imtZ1K0WF8wzS3rVkYIESyOC0HE7lPFZBeNUUBILWtvObjlGQvO50BI94iZVu2tTK2/bjwknS6tYX+hfeIIIyUNjsPOum6jrhxEfqOB88ovBH0MQ/6sPGwJKr+w/XQjD7AYR3Xdc/Fc/JN6I/B2AxgNbU1R8+bEsth9Tpon05K/f+0NGTL2jAxPm1mCB8GavJdSHt6uwqZf0doO5mWGfl24XyJ3z/A4SrVbys=
  template:
    metadata:
      name: mysql-credentials
      namespace: matomo
