# ClusterIssuer Let's Encrypt - DNS Challenge Cloudflare
# =======================================================
# Utilise le DNS Challenge pour valider le domaine (fonctionne avec Tailscale)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-cloudflare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: contact@kubesecurebox.com
    privateKeySecretRef:
      name: letsencrypt-dns-cloudflare-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
        selector:
          dnsZones:
            - kubesecurebox.com
            - alexismetton.com
