# ArgoCD Application - Infrastructure
# ====================================
# Deploie tous les composants d'infrastructure :
# - NFS Provisioner (StorageClass)
# - Sealed Secrets (gestion des secrets)
# - Ingress NGINX (controller d'ingress)
# - cert-manager (certificats Let's Encrypt)
# - ArgoCD Ingress (acces via argocd.kubesecurebox.com)
# - Monitoring (Prometheus, kube-state-metrics, Grafana)
# - Grafana Ingress (acces via grafana.kubesecurebox.com)
# - Loki + Promtail (Helm charts grafana/loki et grafana/promtail, loki-stack déprécié)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-nfs-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AlexisMetton/kubesecurebox_gitops.git
    targetRevision: main
    path: infrastructure/nfs-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AlexisMetton/kubesecurebox_gitops.git
    targetRevision: main
    path: infrastructure/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AlexisMetton/kubesecurebox_gitops.git
    targetRevision: main
    path: infrastructure/ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AlexisMetton/kubesecurebox_gitops.git
    targetRevision: main
    path: infrastructure/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-argocd-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AlexisMetton/kubesecurebox_gitops.git
    targetRevision: main
    path: infrastructure/argocd-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AlexisMetton/kubesecurebox_gitops.git
    targetRevision: main
    path: infrastructure/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-grafana-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AlexisMetton/kubesecurebox_gitops.git
    targetRevision: main
    path: infrastructure/grafana-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Loki (chart "loki" 6.x - loki-stack est déprécié et retiré du repo)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.52.0"
    helm:
      releaseName: loki
      values: |
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        deploymentMode: SingleBinary<->SimpleScalable
        singleBinary:
          replicas: 1
          persistence:
            size: 10Gi
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        loki:
          auth_enabled: false
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage:
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Promtail (envoie les logs vers Loki)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: "6.17.1"
    helm:
      releaseName: promtail
      values: |
        config:
          clients:
            - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
        # Sur Raspberry Pi, Promtail met plus de temps à répondre à /ready
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 6
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true