---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mcp-hub-secrets
  namespace: mcp-hub
spec:
  encryptedData:
    MCP_BOOTSTRAP_ADMIN_TOKEN: AgDLtEyO22JAoa4Z9y4Dhqnv5Si93og2iim89euUQsp+HcaIUlza2YAl9adI8V9f588v9s7oFXBYFVCtwWCQR1VlpcQNjf6RgEtHetIRuUzsxVDl/oNxTfNN079qvsOxHExKQ/NJZ/8ZZdPlqdkHBnTe0dSaVkyh4AYH0TsKQ7idHPey+M4Pr5VJTJtm+mpfNQFLBnMzyyr6JSkiu8qw1Bv84BaJgUOE1YWBufGoI1ogT7Y1sTuE+AAPEXQUwK9xwSFZx/6eWe73qRG6Ka/mk+z2fyzISFq5n1Iw9ZAG+lfGZ8M/OqudB4HNGm7X3tTEFfp3WSL6C4MCWaXPBV3ExyP6NWdtSKu4s5GFxfp5HJoFBdrCyXT6Dsv+cj5MQYPcBCMQ4XbQ1XvAZWRCtH/KF5Q9u5USQFvEwyK7ncCN/HL/6bTlZb2mKRjF5pWpOapPigpEAFF3HzKAh6jQ3UPukCa8daDXL1Am7xFtyp+PJZwiq4171ncQepLcl2B/3LCwYkXxluZ+WTZQ2S+sgSwWMzuZWa1ubQWbR2rU7GDgOfN/YjDSrQC/nf6H57ocCoP2EPgLT6JQAc7Xu3eMxGf0JMJf3PmwOu5pu5+suI9jXDFlf7iGJ0SGKqxqISwqGz+hOxnjTdMHQqkKsMm+9a5DfwvtbnF8mSwLYAu4gI3ZFsEaB2nYDkI0Peo7pTZ6k6vUlkBfnmZv9qey8D29FUjRu1tcN5YLlBwhtckAmG+FayjfjZL6/X+r6ycFTSf+
    RAG_API_TOKEN: AgDbqSXkKiQk7DWyllH5KTr+b+2tN/pUTwPeBLME8g5Km8ms7GLisgxsNQZFZFGuDcZkLpr8cSkHUo9KVIJbos04k+tdu1g8YqE2pQsooO6zhwdHPOvyxqYNML1o84HrcaBXkhwWjFAjfZs0jSBSf9O+tbjdK6HZEr0R5olY5Um6qJ3RyBoSGoPWtkF5Dz8sI/oOJzKtcEBc2uptVI6zEovXXArGmDtcFzMp32h+5eq3pgaNRfuFSFiCUgUFcNh/ZzN5PK3d4nk+mjwKtH7Uw6AbJO/U18su/sRVejZf2yccKVzEQ6Fc/iypWrQfBCi2qAUAnJN5N0Xog9K2qLuGaDGTNUh9O8kNFqQIeB50U/dNd+3dCRVsR2OVbT4UTgC/bPELDOwKkNLUYW2BClKhy35MS3SsMFnIlHm/sf3vJQ0i/cm1+BD4p1Cn0U675VLLaRceZuRoXDxCX7nBuA40eFLaj9Usb/qtLCxw0LLX1lxoQDPkZ5/A/Wc0N4Y7E5ynivlwg0Dets0LGQk0ldis2QRpx45tLRPD6a0NjLTADYbCWU+Pmgqh2KuVH4CzNAXDM0OSVux5Gsqd9xGPtSY9cAa5xUc3DuTAv5Lr9V+aRVbHR5QuN1AfmfGtKVtk4r4bIq71+/ObIDq3VqRP5oEz7qjNBod72GwUm9lnGGo4wLxmLJYqwHY2s8eg7aQa46BHRoZ8vDkb6yGI1Yl5KuC2jxoDPEakp2y6279PGwhM8dP034TxpqXkrRqII2tIfhR6zmrpQ0Osth+Emu09EdJZXJ55
  template:
    metadata:
      creationTimestamp: null
      name: mcp-hub-secrets
      namespace: mcp-hub
    type: Opaque
